In [90]:
"""Program to add a border (filled with 0's) around an given array"""
import numpy as np
row, col = [int(num) for num in input('Enter number of rows & columns respectively:').split()] 
numbers = np.ones((row,col))            # creating numpy of 1s of given size
numbers

Enter number of rows & columns respectively:3 6


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [91]:
new = np.insert(numbers, 0, 0, axis = 0)   # inserting 0s at 0 index of each column 
new                                        # otherwise numpy array given in parameter will be flattened

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [92]:
new = np.append(new,np.zeros((1, new.shape[1])), axis = 0)   # appending row at end with required No. of columns
new                                                         # used numpy.array.shape() gives tuple (rows, columns)

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [93]:
new = np.append(new, np.zeros((new.shape[0],1)), axis = 1)    # appending column with required No. of rows
new                                                          

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [94]:
new = np.insert(new, 0, 0, axis = 1)         # inserting 0s at 0 index of each row i.e. inserting along axis 1 
new

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])