## Program to print array elements with precision

In [12]:
import numpy as np
floats = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 
0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision=3)            # setting precision for printing floats henceforth
floats

array([0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069,
       0.547])

In [15]:
np.array([0.115456451,0.4545454, 0.555555])

array([0.115, 0.455, 0.556])

In [16]:
np.array([0.4568,0.546587454,.0454564])

array([0.457, 0.547, 0.045])