##  Program to add an extra column to an numpy array

In [6]:
import numpy as np
numbers = np.array([[10,20,30],[40,50,60]])      # new column must same numbers of rows
numbers

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
np.append(numbers, [[100],[200]], axis = 1)       # appending new column to gievn 2D array 

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [10]:
np.hstack((numbers,[[100],[200]]))              # alternate way horizontal appending

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])